services:

  postgres-db:
    image: library/postgres:17-alpine
    restart: ${DOCKER_RESTART}
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - workQuest-net
    expose:
      - ${DB_PORT}
    logging:
      driver: "json-file"
      options:
        max-file: "1"   # number of files or file count
        max-size: "25m" # file size

  selenium-web:
    image: selenium/standalone-chrome:138.0
    restart: ${DOCKER_RESTART}
    environment:
      SE_START_VNC: false
    networks:
      - workQuest-net
    #ports:
    #  - "4444:4444"
    ## To see what is happening inside the container, head to http://localhost:7900/?autoconnect=1&resize=scale&password=secret
    #  - "7900:7900" # also commend --headless to see anything
    logging:
      driver: "json-file"
      options:
        max-file: "1"   # number of files or file count
        max-size: "25m" # file size

  kotlin-backend:
    container_name: workQuest-kotlin-backend
    image: eclipse-temurin:21
    mem_limit: ${MEMORY_LIMIT}
    stdin_open: true
    tty: true # with this set to true use Ctrl+P, Ctrl+Q to exit
    restart: ${DOCKER_RESTART}
    working_dir: /var/www
    volumes:
      - ./:/var/www:rw
      - ./.gradle:/.gradle:rw # gradle downloading directory
      - ./.docker/.gradle:/root/.gradle:rw # gradle home cache directory
    command: >
      bash -c './gradlew --no-daemon clean unzipNewrelic build ${GRADLE_ADDITIONAL_ARGUMENTS} \
        && java -XX:+UseSerialGC -Xss512k -Xms256m -Xmx512m  -Dnewrelic.config.file=newrelic/newrelic.yml -javaagent:./build/libs/newrelic/newrelic.jar -jar "./build/libs/workQuest-$(cat /var/www/build.gradle.kts | grep "version = " | grep -Eo "[0-9]+.[0-9]+.[0-9]+").jar"'
    networks:
      - workQuest-net
      - caddy
    labels:
      caddy: ${APP_URL}
      caddy.reverse_proxy: /api* "{{upstreams 8080}}"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - selenium-web
    logging:
      driver: "json-file"
      options:
        max-file: "1"   # number of files or file count
        max-size: "25m" # file size

volumes:
  postgres:

networks:
  workQuest-net:
  caddy:
    external: true