spring:

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}