spring:

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  config:
    import: optional:file:.env[.properties]

  datasource:
    # postgres-db:5432 is set to permanent because it is in same docker network
    url: jdbc:postgresql://postgres-db:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}