spring:

  shell:
    interactive:
      enabled: true
    script:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  config:
    import: optional:file:.env[.properties]

  datasource:
    # postgres-db:5432 is set to permanent because it is in same docker network
    url: jdbc:postgresql://postgres-db:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  tomcat:
    threads:
      max: 10 # https://docs.spring.io/spring-boot/docs/3.2.1/reference/htmlsingle/#application-properties.server.server.tomcat.threads.max
      min-spare: 2
    max-connections: 10