name: Run backend build / test
on: [ push ]
jobs:
  Backend-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: ./gradlew build