name: Run backend build / test
on: [ push ]
jobs:
  Backend-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      #- run: kotlinc -version && java --version # Check kotlin/java version only uncomment when something not working

      - run: ./gradlew build