name: Run backend build / test
on: [ push ]
jobs:
  Backend-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: kotlinc -version && java --version

      - run: ./gradlew build